WC5E/Warcraft-5e-Conversion

- Heroes Handbook, Main File
Changes the names of the orc clans from "Agile Clans" to "Hunter Clans", and "Brute Clans" to "Warroir Clans"
> Rename orc clans

- Heroes Handbook, Main File
Moved "Savage Attack" to Warrior clans, added "Ancestral Call" to Mystic clans, and "Agility" to Hunter clans.
Fixed some minor error as well, warrior/hunter name in the orc clans trait of the base race. As well as the race height.
Also fixed the alphabetical order of the clans, so Warrior isnt in the middle.
> Revised Orc Clan Traits

- Heroes Handbook, Main File
Added Tangerine to the credits
> Updated Credits

- Heroes Handbook, Main File
Redid the human traits so it's not a mirror of whats found in 5e's PHB, and removed the Variant Human option.
> Revised Human Traits

- Heroes Handbook, Main File
Took a crack at revamping the Dwarf, heavily reposition traits onto the subraces instead of them being minor increases and the base race being the chunk of it.
> Revised Dwarven Traits

- Heroes Handbook, Main File
Tried out something a little different for the Draenei. Let me know what you guys think.
> Aternate Draft of New Draenei Traits, from ApolloLumina

- Heroes Handbook, Main File
Nothing has changed, simply fixed the formatting so there wasnt a big empty space on the page!
> Draenei Updated Formatting

- Heroes Handbook, Main File
Revised troll traits, and an added Zandalari subrace. Balance sits at Forest 25, Ice 24, Jungle 26, Zandalari 25.
> Revised Troll Traits

- Heroes Handbook, Main File.txt
Added Gnomish Nimbleness to their traits, and generally fixed some formatting that I was unhappy with.
> 'Revised' Gnome Traits

- Heroes Handbook, Main File.txt
Tweaked a few of the goblin traits
> Revised Goblin Traits

- Heroes Handbook, Main File.txt
With all of the races reworked, many of the racial feats are pretty much useless. Also decided to just go over the normal feats as well while I was at it
> Updated feats

- Heroes Handbook, Main File.txt
Someone pointed out on Reddit that the Assassin subclass needed to have more with poisons to do. I agree that it requires some rework. So scouted around to get some inspiration and put together this.
> Revised Assassin Rogue Subclass

- Heroes Handbook, Main File.txt
Tiny fix in Paladins Spellcasting Ability
> #### Spellcasting Ability format fix

- Heroes Handbook, Main File.txt
A couple of minor tweaks to Shamans, nothing major
> Minor Fixes to Shaman

- Heroes Handbook, Main File.txt
Renamed "Feature Statblocks" to "Shapeshifts"
Added Demon Companions
> Updated toc

- Heroes Handbook, Main File.txt
Reformatted the appendixs, added some code to remove the outline of the monster blocks. and added Demon Companions as Appendix B
> Reformatted Appendixs

- Heroes Handbook, Main File.txt
Changed Appendix B to Appendix C
> Demon Hunter Fix

- Heroes Handbook, Main File.txt
- Tweaked Thrown Weapons so that they can be used with Demon's Bite.
- Added the ability to use Demon's Bite with War Magic
> Demon Hunter Wrath fixes

- Heroes Handbook, Main File.txt
- Changed Charge
- Changed Fury's Bloodthirst
> Warrior Fixes

- Heroes Handbook, Main File.txt
Made it so Tauren monks can't have an ac equal to 10 + dex + wis + con.. cause that's not broken at all
> Updated Tauren Endurance

- Heroes Handbook, Main File.txt
Looked over the Druid and Hunter, and tweaked various minor bits that needed it
> Druid and Hunter Class Tweaks

- Heroes Handbook, Main File.txt
- Slightly changed Unstable Surge
- Renamed the Savants to their magic school
- Reworked Ice Barrier
- Reworked Companion of Ice, and renamed it Ice Familiar
> Various Tweaks

- Heroes Handbook, Main File.txt
Fixed "Life Tap"s name in the Warlock table to correspond with the feature description.
Moved 'Mind Blast' to 2nd level on the Demonology Expanded Spell list, and added 'Charm Person' at 1st level.
> Warlock fixes

- Heroes Handbook, Main File.txt
Went through the book, made sure the page number and footer is gone on the pages it needs to be, pushed some images forward, fixes spell attack and saves to be identical to the phb.
> Minor Fixes

- Heroes Handbook, Main File.txt
I've never been satisfied with the dwarf, and it's still not great. But at least now it follows a similar model to the rest of the races.
> Dwarf "lore" Remake

- Heroes Handbook, Main File.txt
- Added each of the elf subclasses to the elves race, and renamed the Elves race Elf, like all other races.
- Removed the background image for a png of Medivh to make things fit better.
> ToC changes

- Heroes Handbook, Main File.txt
Added Part 3, with the variant rule for Inspiration and Mana.
> Part 3 - Variant Rules

- Heroes Handbook, Main File.txt
- Added the reworked spell list for each class
- Added the new homebrew spells
> Reworked Spell List and Spells

- Heroes Handbook, Main File.txt
Fixed the page numbers in the ToC, and various pages that require manual updating to change formatting.
> Fixed Page Numbers

- Heroes Handbook, Main File.txt
> Nightborne Race

- Heroes Handbook, Main File.txt
Changed Demon Skin from being Self to Touch to match its wording
> Demon Skin tweak

- Heroes Handbook, Main File.txt
Bug in the shaman spell list, duplicated the 4th and 5th level spell lists.
> Fixed Shaman Spell List

- Heroes Handbook, Main File.txt
Healing Rain missed "Rain" in its name
> Healing Rain fix

- Heroes Handbook, Main File.txt
Added Lightning Blast to the Shaman spell list
> Added Lightning Blast

- Heroes Handbook, Main File.txt
Reverts Jihia/Warcraft-Heroes-Handbook#130
> Revert "Reworked Rage Mechanic"

- Heroes Handbook, Main File.txt
Concentrated Souls was poorly worded in how it worked, reworded it to make it clear.
> Concentrated Souls Rewording

- Heroes Handbook, Main File.txt
Changed the Warrior Rage mechanic to be more like what it is in WoW, with the warrior being able to generate rage as they hit an enemy.
> Reworked Rage Mechanic

- Heroes Handbook, Main File.txt
Bear and Cat form now use both their action and bonus action for their attacks, also changed Cat Forms pounce.
> Shapeshift changes

- Heroes Handbook, Main File.txt
Replaced Rallying Cry with Taunt
Replaced Shield Block with Shield Slam
> Protection Warrior reworks

- Heroes Handbook, Main File.txt
- Reworked Shaman
- Spell List
- Appendix B: Shaman Spirits
> Reworked Shaman

- Heroes Handbook, Main File.txt
Reworked the druid, it's shapeshifts. and some small fixes across the document.
> Reworked Druid + Various Fixes

- Manual of Monsters, Main File
Removed the Darkhound to put it into Appendix A
> Removed Darkhound

- Manual of Monsters, Main File
Formatted our current Dinosaurs, and moved Raptors here from Appendix A
> Formatted Dinosaurs

- Manual of Monsters, Main File
This will tidy up the CSS for the document and bring it all together in a single tag at the top of the page, rather than being segmented into multiple tags in different locations.
Also adding some more comments, to better clarify. This is all just housecleaning to make things easier to maintain.
> style: collate css in single tag at the top of doc

- Manual of Monsters, Main File
The layering for the Monster Manual style footers wasn't right. Should fix it.
> style: fix footer layering

- Manual of Monsters, Main File.txt
There's still content missing for the ghost, but this is the first commit to it.
> creature: first-draft ghost text

- Manual of Monsters, Main File.txt
Changed it so Lightning is the default damage type for their breath and spit attacks
> format: wind serpents /w lightning attacks

- Manual of Monsters, Main File.txt
Added a Variant: Treant Wildcaller for a CR 3 druidic treant option.
> format: treant

- Manual of Monsters, Main File.txt
Added 4 additional skeleton monsters to give a broader variety of skellies, some also very iconic for Azeroth
> format: skeletons

- Manual of Monsters, Main File.txt
This formats the text and statblocks for the mechanicals section. No images added yet.
> format: mechanical creatures text and statblocks

- Manual of Monsters, Main File.txt
The layout and art felt a bit weird, so gave it a facelift.
> art: centaurs

- Manual of Monsters, Main File.txt
Formatted the kobolds with artwork and a bit of layout reworking.
> art: kobolds

- Manual of Monsters, Main File.txt
I got Model Viewer to work again, yay!
> art: mechanicals

- Manual of Monsters, Main File.txt
This starts adding in some inkblots to various pages, shifts a few statblocks around a little bit, and adds in a CSS class for anchoring wide statblocks to the bottom of the page.
More work to be done, but let's push this out in increments.
> style: creature art adjustments

- Manual of Monsters, Main File.txt
Formatted the Elementals, and reworked the Arcane Elemental
> art: elementals

- Manual of Monsters, Main File.txt
Added page numbers and jumps in the ToC up to the nearest unfinished monster, Golems in this case.
> ToC page numbers

- Manual of Monsters, Main File.txt
First-draft proposal for an intro text to Chapter 1 in the Manual of Monasters.
> text: draft Ch. 1 introduction

- Manual of Monsters, Main File.txt
renamed them Wretched proper instead of Elf: Wretched since we split up the various elves more.
> art: wretched

- Manual of Monsters, Main File.txt
First page is entirely blank and needs text, just formatted all of the other pages with art pieces.
> art: silithids

- Heroes Handbook, Main File.txt
Cleaned up the credits to correspond with the improved layout of the Manual of Monsters, positioned all of the forms of code at the start of the book so that it is all found in one place.
> credit's cleanup and code positioning

- Heroes Handbook, Main File.txt
Added average HP to each class
> class average hp

- Heroes Handbook, Main File.txt
Reverting the main branch so that it corresponds to the 2.1 version of the Handbook, from there we can add a new branch for 3.0
> Main reverted to 2.1

- Manual of Monsters, Main File.txt
> Update gnolls using new table

- Manual of Monsters, Main File.txt
Rebalanced creatures A-D using the new table. Added links to balance calculations for each creature.
> Auv misc rebalancing

- Heroes Handbook, Main File.txt
Removed Multiclassing entirely as we're baking it into each individual class. Updated the elven feat to properly display their individual names, and removed Mechanical Tinkering as Gnomes no longer have the trait necessary for the feat.
> chapter-5/customization-options

- WIP 3.0 Classes/README.md
- WIP Manual of Monsters/README.md
This adds a new folder for keeping 3.0 class update WIPs, with just a README in it. 
It also adds a README to the same WIP folder for the Manual of Monsters.
> add new WIP 3.0 folder

- Manual of Monsters, Main File.txt
> Size Examples

- Manual of Monsters, Main File.txt
> Update Manual of Monsters, Main File.txt

- WIP 3.0 Classes/Warlock.md
This adds the source from the current 3.0 Warlock playtest to the 3.0 WIP folder.
> class: add warlock 3.0 playtest

- Manual of Monsters, Main File.txt
Fixes #555, fixes #505, fixes #496
> Change creature type of: Furbolgs, murlocs, satyrs

- Manual of Monsters, Main File.txt
- WIP Manual of Monsters/Appendix C - Non Player Characters
- WIP Manual of Monsters/Children of the Aspects
- WIP Manual of Monsters/Dragonflights
Most of the changes are just hp increases. Big changes: For Trogg Ambusher (except the increase in hp) I removed the Parry reaction. For Trogg Shaman (except the increase in hp) I removed the Innate Spellcasting and switched the erupting earth spell with  stinking cloud.
> Geamros misc rebalancing

- WIP 3.0 Chapters/Chapter 1 Races
> Fix various typos

- WIP 3.0 Classes/Mage.md
Removed reprint of Tasha content and replaced it with a note referring to the pages in the book,
> Replaced reprint with note

- Manual of Monsters, Main File.txt
Renamed Naga Sea Witch to Naga Siren, and the Variant stat block to Naga Sorceress.
> Renaming naga spellcasters

- WIP 3.0 Chapters/Chapter 1 Races
Added the Lucky trait to humans, fixed the wrong adjective for Kul Tirans.
closes #740
closes #727
> Update Chapter 1 Races

- WIP Manual of Monsters/Appendix B - Non Player Characters.md
Necromancer art, ranger beast companion note block, tribal warrior/veteran art
> Update Appendix B - Non Player Characters.md

- WIP Manual of Monsters/Cloud Serpents
Put proper formatting on legendary actions
> Cloud Serpent Patch 2

- WIP 3.0 Classes/Mage.md
closes #749 
added errata changelog
> Mage: Sepll errata #749

- WIP Manual of Monsters/Scourge.md
contains changes to wording and a rework for the deathcharger.
Deathcharger also has a variant that is commented out.
> scourge-wording-fixes

- WIP Manual of Monsters/Scourge.md
Reimagined Necrolyte
They are now a pactcaster with a mix of priest and warlock spell.
Necrolyte CR from 3 to 2.
> scourge-necrolyte-rethink

- WIP Manual of Monsters/Dragonflights
Rearrange order of creatures, add in art to greater dragonflight spaces, lots of small bugfixes and formatting checks, added placeholder spots, added variant dragonspawn for infinite and netherwings.
> Dragonflights Patch 1

- Manual of Monsters, Main File.txt
New version, with missing ape creature.
> Update Appendix A - Miscellaneous Creatures

- WIP Manual of Monsters/Appendix B - Non Player Characters.md
- partials/HHB 3.0 Playtest Doc Material.md
Another PR into Appendix B to
- Update the art on more pages
- Change the "Damned" variant to "Acolyte of the Damned" (just a bit of a personal preference thing) and some text changes on it 
- Move the text on the druid page
- Small update to the ranger beast companion variant text
- Update the back-page to reflect team changes
All that remains beyond that, providing all else looks good for the team, is to add the paper notes in, convert them from green notes to the real deal with Figma.
Going to do that in this pull request before it is merged, just have not done it yet. 👍
GMB link to see the contents of this PR 
https://www.gmbinder.com/share/-MTLHvuaLKirneEgmUfF
Note-points of still to do in this PR:
> MM App B: Art updates and text changes

- Collections/Homebrews.md
- Collections/Theme of the Month.md
This adds in the source data for the Theme of the Month and Homebrew GM Binder docs to source control, so they can be edited from here and then rendered via GMB to put as PDFs on Google Drive. 👍
> Add Homebrew and TotM source files to repo

- WIP 3.0 Chapters/Chapter 1 Races
Closes issues #765 , #779 , #750
> Create Chapter 1 Races

- Manual of Monsters, Main File.txt
> Update Cloud Serpents.txt

- WIP 3.0 Classes/Warlock.md
Added in a changelog. Also made some short changes to the credits (removing the old ones), but I don't know where the images came from in terms of bibliography, just where I got them.
The back page formatting got messed up somehow, so I added in some margins to try to make it look like it used to.
> Changelog and Credits

- WIP 3.0 Chapters/Chapter 6 Spells
Fixed an extra listing of Mind Flay in the New Spells By Level list.
> Mind Flay Fix

- Manual of Monsters, Main File.txt
Save DC is missing for Massive Crash. Based on Str it should be 17 (8 + 5 + 4)
> Add save DC for Massive Crash

- WIP 3.0 Classes/Mage.md
This PR is for the HHB 3.1 release candidate of the Mage updates. The document as updated in this PR can be previewed in the pre-release folder on Google Drive here:
https://drive.google.com/file/d/1jct5SrzWz-ejCuJywYPb4GYi684GwnQH/view?usp=drive_link
Aimed at cleaning up some wording, and fix some rendering and formatting issues
> HHB Mage 3.1 Updates candidate

- WIP 3.0 Chapters/Chapter 1 Races
- partials/HHB 3.0 Playtest Doc Material.md
This PR is for the HHB 3.1 release candidate of the Race Chapter updates. The document as updated in this PR can be previewed in the pre-release folder on Google Drive here:
https://drive.google.com/file/d/11bYU9SpPiLhM-WHDrLYQzVg7IPoAtvpE/view?usp=drive_link
> HHB 3.1 Race Chapter updates

- WIP 3.0 Chapters/Chapter 6 Spells.md
> Removed Flame Arrows from Mage spelllist

- WIP 3.0 Chapters/Chapter 6 Spells.md
- WIP 3.0 Classes/Death Knight
- WIP 3.0 Classes/Priest.md
PR to address issues #879, #890, #891 , #892, and with that epic issue #882
> Priest 3.1.1 fixes 

- WIP 3.0 Chapters/Chapter 0 Intro.md
- WIP 3.0 Classes/Mage.md
Just a PR with some quick-fix small things after the HHB 3.1 merge.
> Cleanup after HHB 3.1 merges, use updated stylesheet for Mage doc

- WIP 3.0 Classes/Death Knight
- WIP 3.0 Classes/Druid
- WIP 3.0 Classes/Paladin
- WIP 3.0 Classes/Shaman
- WIP 3.0 Classes/Warlock.md
When I removed the spell list, some of the PDFs renderings didnt present properly, this a PR to update it appropriately
> Updating PDF bugs after removing the Spell list
