WC5E/Warcraft-5e-Conversion

Heroes Handbook, Main File
Moved "Warstomp" to the Bloodhoof tribe and removed thier skill proficiency in replace of "Brave", Reworded Grimtotems Indimidation proficiency, and added "Rugged Tenacity". Removed Highmountains proficiency in animal handling, adding "Beast's Respect" in its place, and added "Mountaineer".
=> Revised Tauren Traits

Heroes Handbook, Main File
Forsakens are difficult to balance because of their undead nature, so Forsaken Elfs got a score of 29, and Humans at 28 on the Detect Balance scale.
=> Revised Forsaken Traits

Heroes Handbook, Main File
A tiny formatting error with the forsakens "Will of the Forsaken" trait, not being in line with the rest of the traits.
=> Forsaken Formatting Error Fix

Heroes Handbook, Main File
The Tauren are now broken up into three regional subraces: Mulgore, Winter, and Hightmountain. The subraces only have a couple of traits and ability scores are not tied to the subraces. I felt that all Tauren share similar ability score increases, but have a couple of different traits based on their subraces. Also, to represent the Tauren's warrior nature and shamanistic tendencies, I have made the second ability score increase STR or WIS, to be chosen at character creation.
=> Tauren Traits Revision

Heroes Handbook, Main File.txt
For whatever reason it was said to Dexterity + Constitution, while it should be Dexterity + Wisdom
=> Fixed Priest 'Unarmored Defense'

Heroes Handbook, Main File.txt
Fixed the class suggestions for Alliance, Ironforge dwarfs were still named Bronzebeards.
- Added a second chocie of Word of Power for 3rd level, as only having 1 til level 10 sucks.
=> Alliance Class Suggestions and Priest Word of Power fix

Manual of Monsters, Main File
It should've been *Explorers' League*, not Explorer's League.
=> writing: fix Explorers' League typo

Manual of Monsters, Main File.txt
One of the vertical half-page stains did not cover the background image properly, allowing it to fade into the other half to much.
=> Spotty Vertical Stain Replaced

Manual of Monsters, Main File.txt
Formatted the wind serpents, and changed the base damage type for their breath attacks to be poison rather than lightning so that there was some semblance between the three wind serpent monsters. Felt weird that one was poison based whilst the other two were lightning based.
=> format: wind serpents

Manual of Monsters, Main File.txt
This updates some parts of the text for the Ancients, and repositions the statblocks to properly line up with the bottom of the page (which is the convention we want to go for).
=> tweak: ancients text and statblock positions

Manual of Monsters, Main File.txt
The Monster Manual page tears in the corners were too far in toward the content, since we're using an A4 page format (as opposed to a US letter format).
This solves that by pushing the page tear with the page number, and the corner arrow with the category number, further out to the side.
=> style: push corner page tears further to the edge

Heroes Handbook, Main File.txt
Silver was stated twice, changed one of them so that it says Electrum
=> standard exchange rates grammatical error

Manual of Monsters, Main File.txt
--Major changes:
-The Eagle, Giant Crab, and Giant Shark had their CRs changed.
-The Hawkstrider lost Shriek and gained Running Leap, in preparation for mounts.
-Giant Eagle, Giant Owl, and Worg lost their Lord of the Rings-inspired traits. Their Intelligences were reduced and they lost their unique languages. The Worg is now a beast and the midpoint between a wolf and dire wolf.
--List of changes:
Boar: Increased hp to 27. 
Brown Bear: Decreased Strength to 15. This reduced attack and damage.
Carrion Bird: Changed d6 hit dice to d8s.
Coyote: Reduced Dexterity to 13. This reduced AC, attack, and damage.
Deer: Reduced damage to 1.
Dire Wolf: Increased Intelligence to 4 and Charisma to 8.
Eagle: Increase CR to 1/8.
Fox: Reduced Dexterity to 11, reducing AC, attack, and damage. Removed …
=> Rebalanced Appendix creatures.

Manual of Monsters, Main File.txt
Yeti: Fixed hit point total, should have been 59 (7d10 + 21). Reduced Intelligence to 6. Fixed wrong average damages.  
Yeti, Abominable: Fixed hit point total, should have been 149 (13d12 + 65). Reduced Strength to 20. Reduced damage on Deadly Leap and Cold Breath. Changed Leap Attack to cost 3 actions and added an inherent jump component. Added Smash Attack Legendary Action. Cleaned up language on a few abilities. Fixed wrong average damages. Fixed wrong DC calculations: now all are based off of Strength or Constitution, as normal.
=> Yeti Updates

partials/HHB 3.0 Playtest Doc Material.md
For easy reusability, this adds a doc in a 'partials' folder here on the project that can be reused as a 'boilerplate' for putting out standalone updates to various content in the Heroes' Handbook -- with the stylesheets, back-page, and so forth already sorted out. 
A bit more convenient than copypasting between different playtest docs? 😄
=> publish playtest doc boilerplate doc for reuse

WIP 3.0 Classes/Mage.md
This branch is open for hotfixing various typos and minor errata popping up the first days following mage-preview-2 being released.
Also just to mark off issues that should be closed with preview-2, since they're still open: 
fixes #605, fixes #683 
Then there is 711, which is in the Death Knight patch Tyloris has up, so it would stay open until that is also resolved. 👍 
Review doc link (last updated for 0fb2d35): 
https://www.gmbinder.com/share/-MRF_5mQ_WVvTVaM1zla
=> mage-preview-2: errata / spelling fixes

WIP 3.0 Classes/Rogue
Disallow redirecting the attack back to the attacker. Closes #748.
=> Adjust wording of Rogue's Trick of the Trade feature (#748)

Manual of Monsters, Main File.txt
Moves the Core Hound and Arcane Golem monster blocks under their respective entries. Before, Core Hound was technically in the Centaur section and the Arcane Golem in the Gnoll section. Also added the missing 'D' capital letter section header to the dinosaur entry.
=> Manual of Monsters: Formatting changes

WIP 3.0 Classes/Shaman
- Change all instances of "the next turn" to clarify whose next turn it is
- Fix grammar ("hit points lasts")
- The "Weapon Strikes" header should probably be an h4, as it's logically a subsection of the Restoration section
=> Small shaman fixes

WIP Manual of Monsters/Scourge.md
When recalculating the Doomskull CR with the new table, and calculator, I somehow assumed you could cast two level 1 spells (hex and magic missile) in the same turn. You can't (but you can cast Hex + Shadow Bolt). I hence lowered the HP to compensate, but that was wrong.
This I discovered when using them in play, so I fixed it and I hereby push back to the project to clean up my own mess.
=> Fix mindfart for Doomskull balance.

WIP 3.0 Classes/Warlock.md
Changes Life Tap to:
- Be able to be used whenever, not just when you are out of spell slots
- Allow you to determine what level the spell is when you cast it, instead of tying it to Fel Sorcery slots (so that you aren't burning enough hit points to power a 5th level version of a non-scaling spell like Alarm)
- Open it up to non-warlock spells, instead being any spell you know (for multiclass shenanigans and feat/racial spells)
- Also clarifies some language, removing reference to an older version of the ability (there is no damage to be resisted)
=> Life Tap patch

WIP 3.0 Chapters/Chapter 1 Races
Hello everyone,
I've updated the languages table for better consistency with official modern lore. You're free to use only parts of this edit or not use it at all.
Justifications for the changes:
Standard Languages:
* Orcish has its own runic writing system instead of using the Common one (source: TFT Maiev mission 2).
* There is no evidence that "Eredic" is a word (zero mentions on Wowpedia). "Eredun", however, is well established, and can work as both the language name and the script name, IMHO.
* Modern Pandaren is not the same language as the Mogu language spoken before the Sundering (source: the quest "[It Was Almost Alive](https://wowpedia.fandom.com/wiki/It_Was_Almost_Alive)", Lorewalker Cho has difficulty translating ancient mogu writing, and [Lorewalker …
=> Reorganize languages for better consistency with modern lore

WIP 3.0 Chapters/Chapter 6 Spells
Changes the name of Summon Undead to Conjure Undead, to prevent confusion with the TCE spell.
=> Summon Undead -> Conjure Undead

WIP 3.0 Chapters/Chapter 6 Spells
Shape Water spell has the "XGE" label in two of the three places. Added missing one
=> fix: add missing XGE label

WIP 3.0 Chapters/Chapter 1 Races
The ethereal who taught Alleria void magic was called [Locus-Walker](https://wowpedia.fandom.com/wiki/Locus-Walker), not Locust-Walker. This PR fixes the name.
=> Fix typo: Locust-Walker -> Locus-Walker

WIP 3.0 Classes/Priest.md
Assuming I did this correctly, this is the edits I did to Llamadom's 3.1.3 priest. Mostly it was cleanup, redoing the class intro, removing the spell list for later, and adding an RP sidebar.
Detailed changelog:
- Overall formatting fixes.
- Many small grammar and spelling checks.
- Completely revised the introduction.
- Added footnote to each page.
- Rearranged the priest class table, removing the Devotion column.
- Added suggested background to quick build section.
- Removed herbalism kit from starting proficiencies. Priests are not known for their skills with herbs.
- Replaced mace with club for starting equipmen, as priests are less martial than clerics. Removed one of the two daggers and herbalism kit from starting equipment and replaced with healer's kit. Added crossbow or simple …
=> Priest 3.1.4

WIP 3.0 Chapters/Chapter 6 Spells
Rain of Fire changed to a cylinder with 6d6 total damage, melts metal, and upscales by 2d6 instead of 1d12 (also material component added).
Fire and Brimstone reflavored to be slithering flames, and increased to 30ft radius from 20ft (also material component added).
Starfire now scales by 1d6 every level instead of 1d12 every two levels.
Dark Void now does psychic damage and calls for a Wisdom save, with some slight reflavoring.
Living Bomb no longer continues until end of concentration, instead ending on a successful save.
Cataclysm now clarifies that the 'aflame' effect only applies from the initial spell damage, not the ground.
=> Chapter 6 Spells Bugfixes

WIP 3.0 Chapters/Chapter 0 Intro.md, WIP 3.0 Chapters/Chapter 1 Races, WIP 3.0 Chapters/Chapter 1 Races.md, WIP 3.0 Classes/Mage.md, WIP 3.0 Classes/Priest.md
This PR is a collection of cleanup and changes for the 3.1 Heroes' Handbook update release. 
Fixing some CSS styles in documents that are being released in 3.1, splitting the frontpage out into a separate doc for the partial previews (right now it has been in the Races document), and updating the contributor list.
=> Document cleanup for HHB 3.1 release
